//------------------------------------------------------------------------------
// <auto-generated>
//     Ten kod został wygenerowany przez narzędzie.
//     Wersja wykonawcza:4.0.30319.42000
//
//     Zmiany w tym pliku mogą spowodować nieprawidłowe zachowanie i zostaną utracone, jeśli
//     kod zostanie ponownie wygenerowany.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Spending.Resources {
    using System;
    
    
    /// <summary>
    ///   Klasa zasobu wymagająca zdefiniowania typu do wyszukiwania zlokalizowanych ciągów itd.
    /// </summary>
    // Ta klasa została automatycznie wygenerowana za pomocą klasy StronglyTypedResourceBuilder
    // przez narzędzie, takie jak ResGen lub Visual Studio.
    // Aby dodać lub usunąć składową, edytuj plik ResX, a następnie ponownie uruchom narzędzie ResGen
    // z opcją /str lub ponownie utwórz projekt VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        /// Zwraca buforowane wystąpienie ResourceManager używane przez tę klasę.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Spending.Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Przesłania właściwość CurrentUICulture bieżącego wątku dla wszystkich
        ///   przypadków przeszukiwania zasobów za pomocą tej klasy zasobów wymagającej zdefiniowania typu.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Back.
        /// </summary>
        internal static string ButtonBack {
            get {
                return ResourceManager.GetString("ButtonBack", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Education.
        /// </summary>
        internal static string CategoryEducation {
            get {
                return ResourceManager.GetString("CategoryEducation", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Entertainment.
        /// </summary>
        internal static string CategoryEntertainment {
            get {
                return ResourceManager.GetString("CategoryEntertainment", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Food.
        /// </summary>
        internal static string CategoryFood {
            get {
                return ResourceManager.GetString("CategoryFood", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Gifts.
        /// </summary>
        internal static string CategoryGifts {
            get {
                return ResourceManager.GetString("CategoryGifts", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Health.
        /// </summary>
        internal static string CategoryHealth {
            get {
                return ResourceManager.GetString("CategoryHealth", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Home.
        /// </summary>
        internal static string CategoryHome {
            get {
                return ResourceManager.GetString("CategoryHome", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Income.
        /// </summary>
        internal static string CategoryIncome {
            get {
                return ResourceManager.GetString("CategoryIncome", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Other.
        /// </summary>
        internal static string CategoryOther {
            get {
                return ResourceManager.GetString("CategoryOther", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Pets.
        /// </summary>
        internal static string CategoryPets {
            get {
                return ResourceManager.GetString("CategoryPets", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Phone.
        /// </summary>
        internal static string CategoryPhone {
            get {
                return ResourceManager.GetString("CategoryPhone", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Shopping.
        /// </summary>
        internal static string CategoryShopping {
            get {
                return ResourceManager.GetString("CategoryShopping", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Subscriptions.
        /// </summary>
        internal static string CategorySubscriptions {
            get {
                return ResourceManager.GetString("CategorySubscriptions", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Transport.
        /// </summary>
        internal static string CategoryTransport {
            get {
                return ResourceManager.GetString("CategoryTransport", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Travel.
        /// </summary>
        internal static string CategoryTravel {
            get {
                return ResourceManager.GetString("CategoryTravel", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Utilities.
        /// </summary>
        internal static string CategoryUtilities {
            get {
                return ResourceManager.GetString("CategoryUtilities", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Vet.
        /// </summary>
        internal static string CategoryVet {
            get {
                return ResourceManager.GetString("CategoryVet", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Export.
        /// </summary>
        internal static string ExportDatabaseButton {
            get {
                return ResourceManager.GetString("ExportDatabaseButton", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Export database:.
        /// </summary>
        internal static string ExportDatabaseText {
            get {
                return ResourceManager.GetString("ExportDatabaseText", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Import.
        /// </summary>
        internal static string ImportDatabaseButton {
            get {
                return ResourceManager.GetString("ImportDatabaseButton", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Import from database:.
        /// </summary>
        internal static string ImportDatabaseText {
            get {
                return ResourceManager.GetString("ImportDatabaseText", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu No transactions found..
        /// </summary>
        internal static string NoTransactionsMessage {
            get {
                return ResourceManager.GetString("NoTransactionsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Add Record.
        /// </summary>
        internal static string RecordViewTab_AddRecord {
            get {
                return ResourceManager.GetString("RecordViewTab_AddRecord", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Edit Record.
        /// </summary>
        internal static string RecordViewTab_EditRecord {
            get {
                return ResourceManager.GetString("RecordViewTab_EditRecord", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Overview.
        /// </summary>
        internal static string RecordViewTab_Overview {
            get {
                return ResourceManager.GetString("RecordViewTab_Overview", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu All.
        /// </summary>
        internal static string SelectableFilterCategory_All {
            get {
                return ResourceManager.GetString("SelectableFilterCategory_All", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Expenses.
        /// </summary>
        internal static string SelectableFilterCategory_Expenses {
            get {
                return ResourceManager.GetString("SelectableFilterCategory_Expenses", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Incomes.
        /// </summary>
        internal static string SelectableFilterCategory_Incomes {
            get {
                return ResourceManager.GetString("SelectableFilterCategory_Incomes", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu (affects app language).
        /// </summary>
        internal static string SettingsCurrencyInfo {
            get {
                return ResourceManager.GetString("SettingsCurrencyInfo", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Currency:.
        /// </summary>
        internal static string SettingsCurrencyText {
            get {
                return ResourceManager.GetString("SettingsCurrencyText", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Settings.
        /// </summary>
        internal static string SettingsTitle {
            get {
                return ResourceManager.GetString("SettingsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu This Month Expenses.
        /// </summary>
        internal static string ThisMonthExpenses {
            get {
                return ResourceManager.GetString("ThisMonthExpenses", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu {0} expense transactions.
        /// </summary>
        internal static string thisMonthExpenseTransactions {
            get {
                return ResourceManager.GetString("thisMonthExpenseTransactions", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu This Month Income.
        /// </summary>
        internal static string ThisMonthIncome {
            get {
                return ResourceManager.GetString("ThisMonthIncome", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu {0} income transactions.
        /// </summary>
        internal static string thisMonthIncomeTransactions {
            get {
                return ResourceManager.GetString("thisMonthIncomeTransactions", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu This Month Net.
        /// </summary>
        internal static string ThisMonthNet {
            get {
                return ResourceManager.GetString("ThisMonthNet", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Total Balance.
        /// </summary>
        internal static string TotalBalance {
            get {
                return ResourceManager.GetString("TotalBalance", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu {0} total transactions.
        /// </summary>
        internal static string TotalTransactions {
            get {
                return ResourceManager.GetString("TotalTransactions", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Add Record.
        /// </summary>
        internal static string TransactionsAddRecord {
            get {
                return ResourceManager.GetString("TransactionsAddRecord", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Overview.
        /// </summary>
        internal static string TransactionsOverview {
            get {
                return ResourceManager.GetString("TransactionsOverview", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Expense.
        /// </summary>
        internal static string TypeExpense {
            get {
                return ResourceManager.GetString("TypeExpense", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Income.
        /// </summary>
        internal static string TypeIncome {
            get {
                return ResourceManager.GetString("TypeIncome", resourceCulture);
            }
        }
    }
}
