//------------------------------------------------------------------------------
// <auto-generated>
//     Ten kod został wygenerowany przez narzędzie.
//     Wersja wykonawcza:4.0.30319.42000
//
//     Zmiany w tym pliku mogą spowodować nieprawidłowe zachowanie i zostaną utracone, jeśli
//     kod zostanie ponownie wygenerowany.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JuanNotTheHuman.Spending.Resources {
    using System;
    
    
    /// <summary>
    ///   Klasa zasobu wymagająca zdefiniowania typu do wyszukiwania zlokalizowanych ciągów itd.
    /// </summary>
    // Ta klasa została automatycznie wygenerowana za pomocą klasy StronglyTypedResourceBuilder
    // przez narzędzie, takie jak ResGen lub Visual Studio.
    // Aby dodać lub usunąć składową, edytuj plik ResX, a następnie ponownie uruchom narzędzie ResGen
    // z opcją /str lub ponownie utwórz projekt VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        /// Zwraca buforowane wystąpienie ResourceManager używane przez tę klasę.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("JuanNotTheHuman.Spending.Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Przesłania właściwość CurrentUICulture bieżącego wątku dla wszystkich
        ///   przypadków przeszukiwania zasobów za pomocą tej klasy zasobów wymagającej zdefiniowania typu.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Add New Record.
        /// </summary>
        internal static string AddNewRecord {
            get {
                return ResourceManager.GetString("AddNewRecord", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu All.
        /// </summary>
        internal static string All {
            get {
                return ResourceManager.GetString("All", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Amount:.
        /// </summary>
        internal static string Amount {
            get {
                return ResourceManager.GetString("Amount", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Do you want to create a backup of the database?.
        /// </summary>
        internal static string BackupDatabaseText {
            get {
                return ResourceManager.GetString("BackupDatabaseText", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Backup database.
        /// </summary>
        internal static string BackupDatabaseTitle {
            get {
                return ResourceManager.GetString("BackupDatabaseTitle", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Back.
        /// </summary>
        internal static string ButtonBack {
            get {
                return ResourceManager.GetString("ButtonBack", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Cancel.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Category:.
        /// </summary>
        internal static string Category {
            get {
                return ResourceManager.GetString("Category", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Clear.
        /// </summary>
        internal static string ClearDatabaseButton {
            get {
                return ResourceManager.GetString("ClearDatabaseButton", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Are you sure you want to clear the database? This action cannot be undone..
        /// </summary>
        internal static string ClearDatabaseConfirmationText {
            get {
                return ResourceManager.GetString("ClearDatabaseConfirmationText", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Clear database:.
        /// </summary>
        internal static string ClearDatabaseText {
            get {
                return ResourceManager.GetString("ClearDatabaseText", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Clear database.
        /// </summary>
        internal static string ClearDatabaseTitle {
            get {
                return ResourceManager.GetString("ClearDatabaseTitle", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Confirm.
        /// </summary>
        internal static string Confirm {
            get {
                return ResourceManager.GetString("Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu All records have been deleted from the database.
        /// </summary>
        internal static string DatabaseClearedText {
            get {
                return ResourceManager.GetString("DatabaseClearedText", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Database cleared.
        /// </summary>
        internal static string DatabaseClearedTitle {
            get {
                return ResourceManager.GetString("DatabaseClearedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu The database is empty..
        /// </summary>
        internal static string DatabaseEmptyText {
            get {
                return ResourceManager.GetString("DatabaseEmptyText", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Database exported successfully.
        /// </summary>
        internal static string DatabaseExportSuccessText {
            get {
                return ResourceManager.GetString("DatabaseExportSuccessText", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Import result.
        /// </summary>
        internal static string DatabaseImportResultsTitle {
            get {
                return ResourceManager.GetString("DatabaseImportResultsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Database successfully imported..
        /// </summary>
        internal static string DatabaseImportSuccessText {
            get {
                return ResourceManager.GetString("DatabaseImportSuccessText", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Import Successful.
        /// </summary>
        internal static string DatabaseImportSuccessTitle {
            get {
                return ResourceManager.GetString("DatabaseImportSuccessTitle", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Date:.
        /// </summary>
        internal static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Are you sure you want to delete this record?.
        /// </summary>
        internal static string DeleteRecordText {
            get {
                return ResourceManager.GetString("DeleteRecordText", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Delete Record.
        /// </summary>
        internal static string DeleteRecordTitle {
            get {
                return ResourceManager.GetString("DeleteRecordTitle", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Edit Record.
        /// </summary>
        internal static string EditRecord {
            get {
                return ResourceManager.GetString("EditRecord", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Education.
        /// </summary>
        internal static string Education {
            get {
                return ResourceManager.GetString("Education", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Entertainment.
        /// </summary>
        internal static string Entertainment {
            get {
                return ResourceManager.GetString("Entertainment", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Error.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Expense.
        /// </summary>
        internal static string Expense {
            get {
                return ResourceManager.GetString("Expense", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Expenses.
        /// </summary>
        internal static string Expenses {
            get {
                return ResourceManager.GetString("Expenses", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Export.
        /// </summary>
        internal static string ExportDatabaseButton {
            get {
                return ResourceManager.GetString("ExportDatabaseButton", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Export database:.
        /// </summary>
        internal static string ExportDatabaseText {
            get {
                return ResourceManager.GetString("ExportDatabaseText", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Food.
        /// </summary>
        internal static string Food {
            get {
                return ResourceManager.GetString("Food", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Gifts.
        /// </summary>
        internal static string Gifts {
            get {
                return ResourceManager.GetString("Gifts", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Health.
        /// </summary>
        internal static string Health {
            get {
                return ResourceManager.GetString("Health", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Home.
        /// </summary>
        internal static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Image Preview.
        /// </summary>
        internal static string ImagePreview {
            get {
                return ResourceManager.GetString("ImagePreview", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Import.
        /// </summary>
        internal static string ImportDatabaseButton {
            get {
                return ResourceManager.GetString("ImportDatabaseButton", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Import from database:.
        /// </summary>
        internal static string ImportDatabaseText {
            get {
                return ResourceManager.GetString("ImportDatabaseText", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Do you want to import data from matching tables?.
        /// </summary>
        internal static string ImportDataQuestion {
            get {
                return ResourceManager.GetString("ImportDataQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Income.
        /// </summary>
        internal static string Income {
            get {
                return ResourceManager.GetString("Income", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Incomes.
        /// </summary>
        internal static string Incomes {
            get {
                return ResourceManager.GetString("Incomes", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Uploaded Image:.
        /// </summary>
        internal static string IsImageUploaded {
            get {
                return ResourceManager.GetString("IsImageUploaded", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Matches.
        /// </summary>
        internal static string Matches {
            get {
                return ResourceManager.GetString("Matches", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Title:.
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu No tables found in database..
        /// </summary>
        internal static string NoTablesMessage {
            get {
                return ResourceManager.GetString("NoTablesMessage", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Doesn&apos;t match.
        /// </summary>
        internal static string NotMatches {
            get {
                return ResourceManager.GetString("NotMatches", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu No transactions found..
        /// </summary>
        internal static string NoTransactionsMessage {
            get {
                return ResourceManager.GetString("NoTransactionsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Other.
        /// </summary>
        internal static string Other {
            get {
                return ResourceManager.GetString("Other", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Pets.
        /// </summary>
        internal static string Pets {
            get {
                return ResourceManager.GetString("Pets", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Phone.
        /// </summary>
        internal static string Phone {
            get {
                return ResourceManager.GetString("Phone", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Add Record.
        /// </summary>
        internal static string RecordViewTab_AddRecord {
            get {
                return ResourceManager.GetString("RecordViewTab_AddRecord", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Edit Record.
        /// </summary>
        internal static string RecordViewTab_EditRecord {
            get {
                return ResourceManager.GetString("RecordViewTab_EditRecord", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Overview.
        /// </summary>
        internal static string RecordViewTab_Overview {
            get {
                return ResourceManager.GetString("RecordViewTab_Overview", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu (affects app language).
        /// </summary>
        internal static string SettingsCurrencyInfo {
            get {
                return ResourceManager.GetString("SettingsCurrencyInfo", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Currency:.
        /// </summary>
        internal static string SettingsCurrencyText {
            get {
                return ResourceManager.GetString("SettingsCurrencyText", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Settings.
        /// </summary>
        internal static string SettingsTitle {
            get {
                return ResourceManager.GetString("SettingsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Shopping.
        /// </summary>
        internal static string Shopping {
            get {
                return ResourceManager.GetString("Shopping", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Subscriptions.
        /// </summary>
        internal static string Subscriptions {
            get {
                return ResourceManager.GetString("Subscriptions", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Success.
        /// </summary>
        internal static string Success {
            get {
                return ResourceManager.GetString("Success", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu This Month Expenses.
        /// </summary>
        internal static string ThisMonthExpenses {
            get {
                return ResourceManager.GetString("ThisMonthExpenses", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu {0} expense transactions.
        /// </summary>
        internal static string thisMonthExpenseTransactions {
            get {
                return ResourceManager.GetString("thisMonthExpenseTransactions", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu This Month Income.
        /// </summary>
        internal static string ThisMonthIncome {
            get {
                return ResourceManager.GetString("ThisMonthIncome", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu {0} income transactions.
        /// </summary>
        internal static string thisMonthIncomeTransactions {
            get {
                return ResourceManager.GetString("thisMonthIncomeTransactions", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu This Month Net.
        /// </summary>
        internal static string ThisMonthNet {
            get {
                return ResourceManager.GetString("ThisMonthNet", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Total Balance.
        /// </summary>
        internal static string TotalBalance {
            get {
                return ResourceManager.GetString("TotalBalance", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu {0} total transactions.
        /// </summary>
        internal static string TotalTransactions {
            get {
                return ResourceManager.GetString("TotalTransactions", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Add Record.
        /// </summary>
        internal static string TransactionsAddRecord {
            get {
                return ResourceManager.GetString("TransactionsAddRecord", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Overview.
        /// </summary>
        internal static string TransactionsOverview {
            get {
                return ResourceManager.GetString("TransactionsOverview", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Transport.
        /// </summary>
        internal static string Transport {
            get {
                return ResourceManager.GetString("Transport", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Travel.
        /// </summary>
        internal static string Travel {
            get {
                return ResourceManager.GetString("Travel", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Type:.
        /// </summary>
        internal static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Expense.
        /// </summary>
        internal static string TypeExpense {
            get {
                return ResourceManager.GetString("TypeExpense", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Income.
        /// </summary>
        internal static string TypeIncome {
            get {
                return ResourceManager.GetString("TypeIncome", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Upload.
        /// </summary>
        internal static string UploadImageButton {
            get {
                return ResourceManager.GetString("UploadImageButton", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Upload image.
        /// </summary>
        internal static string UploadImageText {
            get {
                return ResourceManager.GetString("UploadImageText", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Utilities.
        /// </summary>
        internal static string Utilities {
            get {
                return ResourceManager.GetString("Utilities", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Vet.
        /// </summary>
        internal static string Vet {
            get {
                return ResourceManager.GetString("Vet", resourceCulture);
            }
        }
    }
}
